name: astravedam_app
description: "Astravedam Vedic Astrology App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0  # ADD THIS LINE
  shared_preferences: ^2.2.0  # For storing user data
  intl: ^0.18.0  # For date formatting
  # NEW AUTH DEPENDENCIES
  google_sign_in: ^6.1.5
  flutter_secure_storage: ^9.1.1
  url_launcher: ^6.2.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true